### ISSUE TITLE
output statistics

### ISSUE THREAD

**Issue by ghost** [fsmosca/chess-artist#38]
Maybe write to the console for each player encountered in the pgn file, how many inaccuracies, mistakes, blunders etc he or she made:

30000 games processed
kasparov, 1 blunders, 3 mistakes, 4 inaccuracies
deepblue, 8 blunders, 1 mistakes, 3 inaccuracies

That way one can use it as an evaluation tool of the strength of e.g. a chess program: make a change, let it play 30k games, count how many bl/mis/inac on average the program made.
Repeat for each new version.
You can then graph or so in e.g. a spreadsheet program the progress.

**Comment by ddugovic** [comment]
If anyone feels motivated to do so, please consider the [winning chances](https://github.com/ornicar/lila/blob/80646821b238d044aed5baf9efb7201cd4793b8b/ui/ceval/src/winningChances.ts#L11) and from that (not from raw centipawn loss) somehow judge move accuracy.

**Comment by fsmosca** [comment]
@flok99 

This is interesting when someone let chess artist analyzes many games at once.

Here is what I am thinking so far.
Just create an option to get summary. Example

`chess-artist -infile a.pgn -outfile eval_a.csv -job evalsummary`

This way other files analyzed by chess artist in the past can be processed.

I need to look in detail again how chess artist annotates position like,

`15... c6 $0 {+0.13} ({Better is} 15...b5 16. Bd5 Rb8 17. Qe2 Bd7 {-0.10})`

By reading that info in the annotated game we need a rule of when a move is blunder, mistake etc.

I am aware how Lichess implements this categories the past 1 or 2 years, I am not sure now if they revised this.

I am not sure if chess artist has bad move categories already such as blunder, mistake and inaccuracies.

Defining  those categories is also not easy at all. In my other program chess game analyzer, I have different system of categorizing than what Lichess is doing.

Thanks for the input. I have not much time at the moment to work on chess artist.

**Comment by fsmosca** [comment]
@ddugovic 

Thanks for the info, I will look at it in detail when I got the time.

**Comment by ghost** [comment]
I've implemented it myself, now waiting for fsmosca to give his agree because it uses some code of chess-artist.

**Comment by ghost** [comment]
@fsmosca https://github.com/flok99/my-eval
