### ISSUE TITLE
Analyze test suite to a given depth

### ISSUE THREAD

**Issue by MortenLohne** [fsmosca/chess-artist#45]
When analyzing an epd test suite, is there any way to analyze each position to a certain depth, instead of for n milliseconds? This would make the analysis deterministic and reproducible on different computers.

**Comment by fsmosca** [comment]
Sorry just read it. Will check it later.

Current version does not support search with depth limits.

Do you want it implemented?

**Comment by MortenLohne** [comment]
Thanks! This is a very useful feature.
