### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by shapiro85** [fsmosca/chess-artist#50]
Hi Fsmosca,
Could you please, upgrade Chess-Artist to support Python 3

**Comment by fsmosca** [comment]
The plan is to release chess artist version 1 (with exe file) for python 2. I will not mix python 2 and python 3. Then after version 1, all will be for python 3 (no more python 2). I still have 2 issues to complete for version 1 release, that is detection of material sacrifice and detection of good piece mobility.
