### ISSUE TITLE
"ValueError: could not convert string to float: |"

### ISSUE THREAD

**Issue by emdio** [fsmosca/chess-artist#61]
Running the script under linux I get the next error message:

$ python2.7 chess-artist.py --infile lichess_pgn_2019.10.07_pocpit_vs_Stanislavik.ehRhK0vI.pgn --outfile out_sample.pgn --enginefile /usr/games/stockfish --eval search --job analyze --movetime 5000
Analyzing engine: Stockfish 9 64
Annotating game 1...
side: White, move_num: 1
side: Black, move_num: 1
side: White, move_num: 2
side: Black, move_num: 2
side: White, move_num: 3
side: Black, move_num: 3
side: White, move_num: 4
side: Black, move_num: 4
side: White, move_num: 5
side: Black, move_num: 5
side: White, move_num: 6
side: Black, move_num: 6
side: White, move_num: 7
side: Black, move_num: 7
side: White, move_num: 8
Game move: Qxe2 (0.00), Engine bestmove: Qxe2 (0.06)
Traceback (most recent call last):
  File "chess-artist.py", line 2395, in <module>
    main()
  File "chess-artist.py", line 2383, in main
    g.AnnotatePgn()
  File "chess-artist.py", line 1871, in AnnotatePgn
    curFen, side)
  File "chess-artist.py", line 962, in IsPassedPawnGood
    MgPassedValue = float(passedPawnComment.split()[8])
ValueError: could not convert string to float: |

**Comment by fsmosca** [comment]
Try using Stockfish 10 and up.

**Comment by emdio** [comment]
With Stockfish10 it worked perfectly.
