### ISSUE TITLE
Search Depth

### ISSUE THREAD

**Issue by shapiro85** [fsmosca/chess-artist#72]
Dear Ferdinand,
I hope you're doing well
Could you please help me with this issue (it looks like the search depth is not working)
this is the command line that I am using to analyze a game from move 14-20 and I want the engine to do it at depth 40

chess-artist.py --infile PGN/game.pgn --outfile Analyzed_game.pgn --enginefile G:\CHESS\Engines\SF\SF.exe --enginename "SF" --engineoptions "Threads value 6, Hash value 8192, MultiPV value 3" --eval search --job analyze --depth 40 --movetime 0 --movestart 14 --moveend 20

**Comment by shapiro85** [comment]
I tried the same command line with different depth like --depth 50 ,--depth 60, --depth 100 --etc and without (MultiPV value 3) but no luck.
it looks like --depth value has no effect at all

**Comment by fsmosca** [comment]
--depth is only applicable when analyzing epd and when engine is tested on test epd.

After --help I only get this.
`--depth DEPTH         input analysis depth, (default=0)`
Will improve the help text messages at some point.

**Comment by shapiro85** [comment]
Could you please add depth option when analyzing pgn

**Comment by fsmosca** [comment]
A lot of code will be broken if I will implement search depth limit in game annotation, as the analysis time in game annotation affects the move annotation symbols !!, !, !?, ?!, ? etc.
