### ISSUE TITLE
Python 3.8 and the newest python-chess

### ISSUE THREAD

**Issue by ChameleonRed** [fsmosca/chess-artist#75]
C:\tmp\chess>chess-artist -i ..\chess\one.pgn -o one.png --eval search -e c:\root\chess\stockfish\11\stockfish_20011801_x64_bmi2.exe --job analyze
Analyzing engine: Stockfish 11 64 BMI2
Annotating game 1...
Traceback (most recent call last):
  File "chess-artist.py", line 2583, in <module>
  File "chess-artist.py", line 2571, in main
  File "chess-artist.py", line 1843, in AnnotatePgn
  File "chess-artist.py", line 1654, in SaveMaterialBalance
UnboundLocalError: local variable 'nextNode' referenced before assignment
[22440] Failed to execute script chess-artist

**Comment by ChameleonRed** [comment]
Nothing special.

```
[Event "Rated Blitz game"]
[Site "https://lichess.org/Zk2LNyA8"]
[Date "2020.04.20"]
[Round "-"]
[White "kakarot99"]
[Black "Cezary_Wagner"]
[Result "1-0"]
[WhiteElo "1800"]
[BlackElo "1494"]
[ECO "B50"]
[UTCDate "2020.04.20"]
[UTCTime "19:46:44"]
[Variant "Standard"]
[TimeControl "300+3"]
[Termination "Normal"]

1. e4 c5 2. Nf3 d6 3. c3 Nf6 4. Qc2 Nc6 5. d4 cxd4 6. cxd4 Nxe4 7. Qxe4 
1-0
```

**Comment by fsmosca** [comment]
* Chess artist by default starts its analysis at move 8.
* That particular game ends in 7 moves.

To make it analyze before move 8, use the option --movestart.
For example to start the analysis at move 2, add the option:
`--movestart 2`

**Comment by ChameleonRed** [comment]
Thank you looks strange but works.

śr., 13 maj 2020 o 02:39 fsmosca <notifications@github.com> napisał(a):

**Comment by fsmosca** [comment]
* What do you mean by strange?
* What OS do you use to run chess-artist?
* What version of chess artist do you use?
