### ISSUE TITLE
generate simple puzzle

### ISSUE THREAD

**Issue by ghost** [fsmosca/chess-artist#80]
i have simple game
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "1/2-1/2"]
[PlyCount "7"]

1. e4 e5 2. Bc4 Bc5 3. Qh5 d6 4. Qd1 1/2-1/2

how can i use --job createpuzzle to make epd to show 4Qf7# as puzzle, thanks

**Comment by fsmosca** [comment]
Try [this](https://github.com/fsmosca/PgnToEpd) instead.

![img](https://camo.githubusercontent.com/901466590b7b07d8ffbdca42655c8c8830a8f771420f50a8ebada7f07626cff7/68747470733a2f2f692e696d6775722e636f6d2f42446752704d722e706e67)

**Comment by fsmosca** [comment]
It cannot, its current algorithm cannot recognize such position.

Use [chess chiller](https://github.com/fsmosca/chess-chiller) instead.

**Comment by ghost** [comment]
what command to use with chiller to get 4Qf7#  to epd file

**Comment by fsmosca** [comment]
`python chess-chiller.py --inpgn sample.pgn --engine stockfish.exe --threads 1 --hash 128`

Save that game to sample.pgn file. Get stockfish engine. Install requirements of chess chiller.

**Comment by ghost** [comment]
command ok for run chiller but no epd file made, need other options maybe

**Comment by fsmosca** [comment]
I review the code in chess-chiller and it will only start checking the moves in the game from move 16. So it was not able to check the moves because the sample pgn is only up to move 4. I am revising this now and will upload later with settable start move number.

Another issue with chess-chiller is that if the move is not complicated and the move is a capture it will not save the position as a puzzle.

#### Command line from updated chess-chiller but not yet uploaded.
```python
python chess-chiller.py --inpgn ./PGN/sample.pgn --engine ./Engine/stockfish_10_x64.exe --threads 1 --hash 128 --log  debug --analysis-start-move 2 --maxtime 5
```

Log from that sample pgn.
```python
2021-01-27 17:39:46,472 [MainThread] [analyze_game] [INFO ] > game move       : h5d1 (Qd1)
2021-01-27 17:39:46,472 [MainThread] [analyze_game] [INFO ] > complexity      : 0
2021-01-27 17:39:46,472 [MainThread] [analyze_game] [INFO ] > best move 1     : h5f7, best score 1: 31999
2021-01-27 17:39:46,472 [MainThread] [analyze_game] [INFO ] > best move 2     : d2d4, best score 2: 367
2021-01-27 17:39:46,473 [MainThread] [analyze_game] [INFO ] > scorediff       : 31632
2021-01-27 17:39:46,473 [MainThread] [analyze_game] [WARNI] > Skip this pos, bm1 is a capture and pos complexity is below 2
```

It sees the best move h5f7 but was not saved.

In order for the position to be saved, I need to disable the complexity requirement. I add `--disable-complexity` flag in the command line.

```python
python chess-chiller.py --inpgn ./PGN/sample.pgn --engine ./Engine/stockfish_10_x64.exe --threads 1 --hash 128 --log  debug --analysis-start-move 2 --maxtime 5 --disable-complexity
```

The outputs epd and pgn files:  
```
rnbqk1nr/ppp2ppp/3p4/2b1p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - bm Qxf7#; ce 31999; sm Qd1; acd 21; acs 5; fmvn 4; hmvc 0; pv Qxf7#; c0 "? - ?, ?, ?, ????.??.??, R?"; c1 "Complexity: 0"; c2 "bestscore2: 367"; c3 "Analyzing engine: Stockfish 10 64";
```

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[FEN "rnbqk1nr/ppp2ppp/3p4/2b1p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 4"]
[PlyCount "7"]

4. Qxf7# *
```

I will upload the latest chess-chiller later or tomorrow after some documentations.

**Comment by fsmosca** [comment]
See latest chess-chiller it is now updated.  

Your typical command line:  
```python
python chess-chiller.py --inpgn mysample.pgn --engine ./Engine/stockfish_10_x64.exe --threads 1 --hash 128 --analysis-start-move 2 --maxtime 5 --disable-complexity
```

**Comment by ghost** [comment]
thank you
maybe have command option save position before blunder
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "1-0"]
[SetUp "1"]
[FEN "rnbqk1nr/pppp1ppp/8/2b1p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 0 3"]
[PlyCount "2"]

3... d6 4. Qxf7# 1-0

**Comment by fsmosca** [comment]
Could you post your new issue in chess chiller repository. 

Perhaps we can close this issue now.

**Comment by ghost** [comment]
ok thank you
