### ISSUE TITLE
Errors in some games

### ISSUE THREAD

**Issue by Kraulfisch** [fsmosca/chess-artist#82]
Hey, after creating thousands of puzzles, I got one error multiple times:

Traceback (most recent call last):
  File "chess_artist.py", line 2717, in <module>
    main()
  File "chess_artist.py", line 2708, in main
    g.CreatePuzzle()
  File "chess_artist.py", line 2536, in CreatePuzzle
    game = chess.pgn.read_game(h)
  File "C:\Users\Raoul Sidler\anaconda3\lib\site-packages\chess\pgn.py", line 1661, in read_game
    line = handle.readline()
  File "C:\Users\Raoul Sidler\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 3765: character maps to <undefined>

It doesn't really bother me, becauese I just edit the pgn file and delete every analyzed game and continue running the programm, I just wanted to report it to you.

The PGN where it happened were the following:

[Event "Graz Open A 2016"]
[Site "Graz AUT"]
[Date "2016.02.18"]
[Round "8.1"]
[White "Turov, Maxim"]
[Black "Li, Chao2"]
[Result "0-1"]
[WhiteElo "2603"]
[BlackElo "2751"]
[ECO "D17"]
[EventDate "2016.02.12"]
[WhiteTitle "GM"]
[BlackTitle "GM"]
[Opening "QGD Slav"]
[Variation "Krause attack"]
[WhiteFideId "4120086"]
[BlackFideId "8604436"]

1.d4 d5 2.c4 c6 3.Nc3 Nf6 4.Nf3 dxc4 5.a4 Bf5 6.Ne5 Na6 7.f3 Nd7 8.Nxd7 
Bxd7 9.e4 e5 10.Bxc4 exd4 11.Ne2 Be6 12.Bxa6 Qa5+ 13.Kf2 bxa6 14.Nxd4 Rd8 
15.Be3 Bc5 16.Rc1 Bb6 17.b3 Qb4 0-1

and

[Event "TCh-ESP Div Honor 2014"]
[Site "Linares ESP"]
[Date "2014.09.04"]
[Round "1.4"]
[White "Antipov, Mikhail Al"]
[Black "Salgado Lopez, Ivan"]
[Result "1-0"]
[WhiteElo "2508"]
[BlackElo "2619"]
[ECO "B40"]
[EventDate "2014.09.04"]
[WhiteTitle "GM"]
[BlackTitle "GM"]
[Opening "Sicilian defence"]
[WhiteTeam "CLUB MAGIC EXTREMADURA"]
[BlackTeam "SESTAO NATURGAS ENERGIA"]
[WhiteFideId "4107012"]
[BlackFideId "2257327"]

1.e4 c5 2.Nf3 e6 3.b3 d6 4.Bb2 e5 5.g3 Nc6 6.Bg2 g6 7.O-O Bg7 8.d3 Nge7 9.
Nh4 O-O 10.f4 exf4 11.Bxg7 Kxg7 12.gxf4 f5 13.Qe1 fxe4 14.dxe4 Nd4 15.Na3 
Bg4 16.Kh1 Nec6 17.c3 Ne2 18.f5 Ne5 19.Bf3 Bxf3+ 20.Nxf3 Nf4 21.Qd2 Ned3 
22.Ne1 Qe7 23.Qe3 Rxf5 24.Nxd3 Nd5 25.Qe2 Nxc3 26.Qg2 Rg5 27.Qf3 Nxe4 28.
Nf2 Nxf2+ 29.Rxf2 d5 30.Re2 Re5 31.Rae1 Rxe2 32.Rxe2 Qf7 33.Qxf7+ Kxf7 34.
Nb5 b6 35.Kg2 a6 36.Nc7 Rd8 37.Re5 d4 38.Kf3 Rd7 39.Nd5 b5 40.Ke4 a5 41.
Nf4 c4 42.Rxb5 d3 43.Rd5 Re7+ 44.Kf3 g5 45.Nh3 cxb3 46.axb3 h6 47.Rxd3 Ra7
48.Rd6 Kg7 49.Nf2 a4 50.bxa4 Rxa4 51.Ne4 Ra2 52.Kg3 Ra4 53.Nc5 Rc4 54.Nd3 
Ra4 55.Ne5 Ra3+ 56.Rd3 Rxd3+ 57.Nxd3 Kg6 58.Ne1 Kf5 59.Kf3 h5 60.Ng2 Ke5 
61.Ne3 Kf6 62.Ke4 Ke6 63.Nd5 g4 64.Nf4+ Kf6 65.Nxh5+ Kg5 66.Ng3 Kh4 67.Kf5
Kh3 68.Nf1 Kh4 69.Ke4 1-0

and

[Event "TCh-CRO Div 1a 2014"]
[Site "Bol CRO"]
[Date "2014.10.07"]
[Round "4.1"]
[White "Kurajica, Bojan"]
[Black "Jovanovic, Zoran CRO"]
[Result "1/2-1/2"]
[WhiteElo "2511"]
[BlackElo "2561"]
[ECO "E60"]
[EventDate "2014.10.04"]
[WhiteTitle "GM"]
[BlackTitle "GM"]
[Opening "King's Indian, 3.Nf3"]
[WhiteTeam "GSK SOLIN-CEMEX Solin"]
[BlackTeam "SK LIBURNIJA Rijeka"]
[WhiteFideId "14400057"]
[BlackFideId "14505320"]
[EventType "team-tourn"]

1.Nf3 Nf6 2.d4 g6 3.c4 Bg7 4.g3 c5 5.Bg2 O-O 6.O-O cxd4 7.Nxd4 d5 8.cxd5 
Nxd5 9.Nc3 Nxc3 10.bxc3 Qc7 11.Rb1 Nc6 12.Nxc6 bxc6 13.Qa4 Bf5 14.e4 Be6 
15.Bf4 Be5 16.Be3 Bxc3 17.Rfc1 Qa5 18.Qxa5 Bxa5 19.Rxc6 Bb6 20.Bxb6 axb6 
21.Rcxb6 Rxa2 22.h4 Rd8 23.Rb8 Rd2 24.Rxd8+ Rxd8 25.Rb7 Rd7 26.Rxd7 Bxd7 
27.f4 f6 28.Kf2 e5 29.fxe5 fxe5 30.Bf3 Kf7 1/2-1/2

There was also one which I didn't saved, but the FEN was this: 5k2/8/p2K1P2/Pp2R2B/8/8/2p5/1r6 b and Black played Rd1+ as the last move.

**Comment by Kraulfisch** [comment]
Also happened in this game:

[Event "6. Rethymno Open 2014"]
[Site "Rethymno GRE"]
[Date "2014.07.19"]
[Round "9.6"]
[White "Rychagov, A"]
[Black "Zinchenko, Yaroslav"]
[Result "1/2-1/2"]
[WhiteElo "2543"]
[BlackElo "2532"]
[ECO "D85"]
[EventDate "2014.07.12"]
[WhiteTitle "GM"]
[BlackTitle "GM"]
[Opening "Gruenfeld"]
[Variation "exchange variation"]
[WhiteFideId "4119932"]
[BlackFideId "14110547"]

1.d4 Nf6 2.c4 g6 3.Nc3 d5 4.cxd5 Nxd5 5.Bd2 Nb6 6.e4 Qxd4 7.Qc2 Nc6 8.Nf3 
Qc5 9.Be3 Qa5 10.Bd2 Qc5 11.Be3 1/2-1/2

**Comment by fsmosca** [comment]
Thanks I will check these games. This is related to the library python-chess package that chess_artist is using.

**Comment by fsmosca** [comment]
I copy paste your posted game and it worked just fine.

If you can share your pgn file, I might be able to duplicate this issue.

**Comment by Kraulfisch** [comment]
[core10.txt](https://github.com/fsmosca/chess-artist/files/6269412/core10.txt)

Sure. In this file it happened at Game number 3027. I can also upload the other ones, if you want them.

**Comment by fsmosca** [comment]
Thanks I got the file and able to reproduce the error.

Will upload the fix later. I am testing it with 500K games from weekinchess from year 2018 to 2020.

**Comment by fsmosca** [comment]
This is now fix in chess artist v2.30.0. Tested with 500K games without errors.

If you encounter pgn errors send me the file.
