### ISSUE TITLE
Ignores files having all caps PGN extension

### ISSUE THREAD

**Issue by drai8192** [fsmosca/chess-artist#85]
How to reproduce:
1. go to PGN folder and rename skillingopp20.pgn to skillingopp20.PGN
2. edit analyze_chess_game.bat and change input file to skillingopp20.PGN
3. run analyze_chess_game.bat
4. it instantly finishes, and chess_artist_log.txt contains only 2 lines, DEBUG :: >> uci and DEBUG :: >> quit

If you rename the input file to .pgn, and use that file name in the bat, it works OK...

Chess Artist v3.1.0 on Windows 10, Python 3.10.0

**Comment by fsmosca** [comment]
Issue is fixed in this commit https://github.com/fsmosca/chess-artist/commit/56f7732dfbdb5ca3190ecff9d8e5340bf3a7b5b4

Thanks.

**Comment by drai8192** [comment]
Thank you, it works now
