### ISSUE TITLE
Depth not working?

### ISSUE THREAD

**Issue by KisaOne** [fsmosca/chess-artist#86]
With ne new version --depth is not working anymore only --movetime.
Is this right? I tried with Stockfish 15 and different hardware.

**Comment by fsmosca** [comment]
What command line did you use?

**Comment by KisaOne** [comment]
Chess Artist works fine with:
chess_artist.exe --infile xxx.pgn --outfile ana_xxx.pgn --enginefile stockfish_22042208_x64_bmi2_1.exe --engineoptions "Threads value 4, Hash value 2048" --movetime 1000 --movestart 1 --job analyze --eval search --log --wordycomment

But it doesn't work with:
chess_artist.exe --infile xxx.pgn --outfile ana_xxx.pgn --enginefile stockfish_22042208_x64_bmi2_1.exe --engineoptions "Threads value 4, Hash value 2048" --movetime 0 --depth 12 --movestart 1 --job analyze --eval search --log --wordycomment

I tried not to use "--movetime 0" but even than it doesn't work.

There is no error message but nothing happens.

**Comment by fsmosca** [comment]
Unfortunately analyzing the game with depth is not supported see the reason in this [issue](https://github.com/fsmosca/chess-artist/issues/72).

**Comment by KisaOne** [comment]
Thank you, your tool is however very good. Maybe you will be able to add the function of depth with pgn. I wish you all the best, stay healthy!

**Comment by fsmosca** [comment]
Thanks you take care too.
